behaviors:
  Pong:
    trainer_type: ppo
    max_steps: 4000000
    summary_freq: 50000
    self_play:
      window: 10 
      play_against_latest_model_ratio: 0.5
      save_steps: 20000
      swap_steps: 10000
      team_change: 10000
engine_settings:
  time_scale: 1